
logLevel = "INFO"

defaultEntryPoints = ["http", "https"]

[api]
  entryPoint = "dashboard"
  dashboard = true

[retry]

# Connection to docker host system (docker.sock)
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "dev.tribus.studio"
  watch = true
  exposedByDefault = false

[entryPoints]

  [entryPoints.dashboard]
  address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
      users = [
        "admin:$apr1$4aB5vCSt$t2kBK2Vxu81tc.mvzi4he1"
      ]

  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
  address = ":443"

    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
      ]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/certs/mindfulhub.crt"
      keyFile = "/etc/certs/mindfulhub.key"


[acme]
  email = "wilco@nurf.com"
  storage = "acme.json"
  entryPoint = "https"
  acmeLogging = true
  onDemand = false
  OnHostRule = true
  caServer = "https://acme-v02.api.letsencrypt.org/directory"

[acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0