## static configuration
# traefik.toml

[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[log]
  level = "DEBUG"

[api]
  insecure = true
  dashboard = true

#[entryPoints.dashboard]
#  address = ":8080"
#  [entryPoints.dashboard.auth]
#    [entryPoints.dashboard.auth.basic]
#      users = ["admin:$apr1$YXSW3aIw$mhZkCYMYHOS6/9BY5TAct."]

[entryPoints.web]
  address = ":80"

[entryPoints.web-secure]
  address = ":443"

##---------------------##

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

# [certificatesResolvers.sample.acme]
#   email = "wilco@nurf.com"
#   storage = "acme.json"
#   [certificatesResolvers.sample.acme.httpChallenge]
#     # used during the challenge
#     entryPoint = "web"

# [http.routers.api]
#   rule = "Host('traefik.docker.localhost')"
#   entrypoints = ["web-secure"]
#   service = "api@proxy"
#   middlewares = ["myAuth"]
#   [http.routers.api.tls]

# [http.middlewares.myAuth.basicAuth]
#   users = [
#     "admin:$apr1$4aB5vCSt$t2kBK2Vxu81tc.mvzi4he1"
#   ]
