debug = false
logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

# WEB interface of Traefik - it will show web page with overview of frontend and backend configurations
#[web]
#address = ":8080"
#  [web.auth.basic]
#  users = ["admin:$apr1$4aB5vCSt$t2kBK2Vxu81tc.mvzi4he1"]

[api]
  entryPoint = "traefik"

[retry]

# Connection to docker host system (docker.sock)
[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "tribus.studio"
  watch = true
  exposedByDefault = false

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
    address = "monitor.dev.tribus.studio:80"
    [entryPoints.traefik.auth.basic]
    users = ["admin:$apr1$4aB5vCSt$t2kBK2Vxu81tc.mvzi4he1"]


[acme]
  email = "wilco@nurf.com"
  storage = "acme.json"
  entryPoint = "https"
  acmeLogging=true
  onDemand=false
  OnHostRule=true

[acme.dnsChallenge]
  provider = "digitalocean"
  delayBeforeCheck = 0