version: "3.2"

secrets:
  digitalocean_api_token:
    file: ./certbot/digitalocean.key

services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: "${PROJECT_NAME}_traefik"
#    restart: unless-stopped
    networks:
      - proxy
#      - internal
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
      - 8025
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs/:/etc/certs/:ro # This is a mount of the certs folder
    environment:
      DO_AUTH_TOKEN_FILE: /run/secrets/digitalocean_api_token
    secrets:
      - digitalocean_api_token
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.port=8080'
      - 'traefik.domain=monitor.${PROJECT_BASE_URL}'
      - 'traefik.frontend.rule=Host:monitor.${PROJECT_BASE_URL}'
      # - 'traefik.docker.network=proxy'
      - 'traefik.enable=true'
      - 'traefik.frontend.headers.forceSTSHeader=true'
      - 'traefik.frontend.headers.STSSeconds=315360000'
      - 'traefik.frontend.headers.STSIncludeSubdomains=true'
      - 'traefik.frontend.headers.STSPreload=true'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.backend=${PROJECT_NAME}_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

  # opensmtpd:
  #   container_name: "${PROJECT_NAME}_opensmtpd"
  #   image: wodby/opensmtpd:$OPENSMTPD_TAG
  #   expose:
  #     - 25
  #   networks:
  #     - smtp
    # environment:
    #   -
    # labels:
      # - 'traefik.enable=true'
      # - 'traefik.docker.network=proxy'
      # - 'traefik.domain=opensmtpd.${PROJECT_BASE_URL}'
      # - 'traefik.backend=${PROJECT_NAME}_opensmtpd'
      # - 'traefik.port=25'
      # - 'traefik.frontend.rule=Host:opensmtpd.${PROJECT_BASE_URL}'
    
      
networks:
  proxy:
    external:
      name: proxy
  smtp:
    external:
      name: smtp

#  internal:
#  breakout:
#    external:
#      name: breakout_d8_docker_default
